<?php

// REFERENCE ONLY — this file is the shape of upload-config.php.
// The real upload-config.php is generated by scripts/generate-upload-config.mjs
// during CI from GitHub Secrets, then FTP-deployed alongside the build.
// You do NOT need to log into Hostinger or edit this on the server.
//
// GitHub Secrets that feed the generator:
//   SUPABASE_JWT_SECRET   -> 'jwt_secret'
//   ADMIN_EMAILS          -> 'admin_emails' (comma-separated)
//   MIGRATION_TOKEN       -> 'migration_token' (leave empty in normal operation)
//
// The uploads directory is auto-created by upload.php on first write (see the
// mkdir() call inside handleUpload()), so it does not need to exist beforehand.

return [
    // Supabase Dashboard → Project Settings → API → JWT Secret.
    // Used to verify the Authorization: Bearer <jwt> header (HS256).
    'jwt_secret' => 'PASTE-SUPABASE-JWT-SECRET-HERE',

    // Lowercase admin email addresses that are allowed to upload/delete.
    // Matched against the JWT `email` claim. Keep this in sync with
    // public.admin_users.
    'admin_emails' => [
        'admin@theciovision.local',
    ],

    // Absolute filesystem path where uploaded files are stored.
    // On Hostinger this is usually something like:
    //   /home/u123456789/domains/theciovision.com/public_html/uploads
    // The default below assumes upload.php is at the document root.
    'uploads_path' => __DIR__ . '/uploads',

    // Public URL prefix that maps to uploads_path. No trailing slash.
    'uploads_url' => 'https://theciovision.com/uploads',

    // ONE-TIME bulk migration token. Leave as '' in normal operation.
    // Set to a long random string (>= 32 chars) only while running
    // scripts/migrate-storage-to-hostinger.mjs, then clear it again.
    'migration_token' => '',
];
